### ISSUE TITLE
Chunk problem

### ISSUE THREAD

**Issue by carlok** [David-Woroniuk/Historic_Crypto#1]
Hello, thanks for your work.
I might have found an odd behaviour.
It seems that with a single chunk or two chunks, the time order changes.
See

```
import datetime

from Historic_Crypto import HistoricalData

signal = 'ETH-EUR'
granularity = 86400
days = 300 # try 300 or 301
date_start = (datetime.datetime.now() - datetime.timedelta(days + 1)).strftime('%Y-%m-%d-00-00')
date_end = (datetime.datetime.now() - datetime.timedelta(1)).strftime('%Y-%m-%d-00-00')

print(HistoricalData(signal, granularity, date_start, date_end).retrieve_data(), signal)
```

As in the comment, try with 300 (single chunk) and 300 (two chunkes)
300 => from new to old
301 => from old to new

**Comment by David-Woroniuk** [comment]
Hi Carlo,

Thanks for spotting this, I assumed that the sort_index argument would take care of this - it is likely due to the different calls within the if/else branch relating to the 300 or larger sample.

Best,

David
