### ISSUE TITLE
Annoying typo in module name Cyptocurrencies (should be Cryptocurrencies)

### ISSUE THREAD

**Issue by jmfrank63** [David-Woroniuk/Historic_Crypto#11]
This is unpleasant, as correcting it might break the API. However, it should be addressed, as your module is very useful and will be used in the future.

You might do a deprecation warning in first and announce breaking changes once you bump to 1.0 remove the old name.

If you are interested, I could try to address this.

**Comment by David-Woroniuk** [comment]
This is a typo in the script name and has been modified. It is not persistent within the old package therefore does not require a deprecation warning.
