### ISSUE TITLE
Finding earliest start date

### ISSUE THREAD

**Issue by armarion** [David-Woroniuk/Historic_Crypto#15]
It would be nice if there was an option to pull data from the earliest available start date. Is there a way to do that?

**Comment by David-Woroniuk** [comment]
Hi @armarion - I can set the ```start_date``` variable as equal to the earliest date as a default (as with the ```end_date``` defaulting to today). Do you have the first date at which market data is available from CoinBase? I imagine this could be an issue when querying different tickers, as the start date is likely not homogenous?

**Comment by David-Woroniuk** [comment]
@armarion - is this still relevant? If you have the ```start_date``` for each variable, I can add this :)
