### ISSUE TITLE
Use asyncio or multithreading for requests

### ISSUE THREAD

**Issue by deepsp94** [David-Woroniuk/Historic_Crypto#16]
I think requests should be called with multithreading/asyncio instead of like so: https://github.com/David-Woroniuk/Historic_Crypto/blob/53b46d50c4ec5295c2e5d2036c0187e6d20acb05/HistoricalData.py#L163

Could you elaborate on why you're doing it this way? Has this got something to with rate limits?

**Comment by David-Woroniuk** [comment]
Whilst I would use asyncio, the Coinbase API does not handle asynchronous requests well, and has a maximum of 300 per message, as per their documentation

![image](https://user-images.githubusercontent.com/70294884/186392277-bfbc46db-ad5a-431e-b6db-345c805c5028.png)


To limit this, I implemented using the below:

```python
        else:
            # The api limit:
            max_per_mssg = 300
            data = pd.DataFrame()
```

Full docs:

https://docs.cloud.coinbase.com/exchange/docs/rest-rate-limits

**Comment by David-Woroniuk** [comment]
Closing as no further interaction. 12:15 27/10/2022
