### ISSUE TITLE
Cryptocurrencies return all ?

### ISSUE THREAD

**Issue by emmanuelvargas** [David-Woroniuk/Historic_Crypto#5]
Hello

sorry if i misunderstood but it seems the find_crypto_pairs() return all the products from coinbase instead of returning only the search requested

return outcome
instead of
return data

in  Cryptocurrencies.py

but maybe I misunderstood this

**Comment by David-Woroniuk** [comment]
Hello,

Thanks for your note.

The find_crypto_pairs()  function is a "finder" function, as denoted by the docs. This should be evident by the input arguments.

Closing.
