### ISSUE TITLE
HistoricalData retrieve_data for different granularities

### ISSUE THREAD

**Issue by noahfeilbogen** [David-Woroniuk/Historic_Crypto#6]
![Screen Shot 2021-05-21 at 5 29 55 PM](https://user-images.githubusercontent.com/17262120/119200116-49a05780-ba5a-11eb-8faa-62f66ed57c7a.png)

Why does HistoricalData().retrieve_data() return different values depending on the granularity input?

**Comment by David-Woroniuk** [comment]
Hi Noah,

This is not an issue with the package - but can be investigated through the documentation around the underlying CoinBase Pro API. If you have any suggestions on how the wrapper can be improved/ changed to mitigate the underlying, please reopen the issue.
